# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b7deee8c15949cffdc08c91ac1d53e5c6ce5cc3427338da459bf13c06feeb2bec9556bc2d5d4fbe9fb24444e91377e5e6a3996e8a58ece4275b2f380dfc9944

test:
  secret_key_base: 2dabc12b5bb142aa0277727da80e2221f9cbe8666dda627782bf8111d76dd7ca8fd1eab080bc66fa2243b322aca8f7168ec8822a76954835cc2c7befb48dd6df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
